---
# Inventory plugin config file name purposely contains "terraform_state" so the
# cloud.terraform.terraform_state plugin recognizes and validates it.
plugin: cloud.terraform.terraform_state
strict: False
backend_type: local
backend_config:
  path: ../../terraform/environments/k3s-dev/terraform.tfstate

groups:
  k3s_control: control_plane_ips
  k3s_workers: worker_ips
  k3s_gpu: gpu_worker_ips
