apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/example-service.yaml
images:
  - name: ghcr.io/your-org/example-service
    newTag: dev
patchesStrategicMerge: []
commonLabels:
  app.kubernetes.io/managed-by: em-infra-dev
